### PR TITLE
replace text with textarea for bio #93

### PR DESCRIPTION
**Pull request by vishalsodani**

### CODE REVIEW

**Comment by alepez** [comment]
Thanks

**Comment by alepez** [comment]
Unfortunately, textarea breaks responsive layout.

image

**Comment by alepez** [comment]
I think (but I'm not sure) we have to manage this issue with purecss grid https://purecss.io/forms/

**Comment by vishalsodani** [comment]
> I think (but I'm not sure) we have to manage this issue with purecss grid https://purecss.io/forms/

ok. I have updated; please check now.

**Comment by vishalsodani** [comment]
@alepez Good catch!

**Comment by alepez** [comment]
I don't know why, but it seems that `pure-input-1-1` is not working as expected, while `pure-input-1` yes.

You should get something like this, adding `pure-input-1` to input and textarea elements.

image

**Comment by alepez** [comment]
```diff
diff --git a/devand-ui/src/app/components/settings_page.rs b/devand-ui/src/app/components/settings_page.rs
index 0781d66..b82a303 100644
--- a/devand-ui/src/app/components/settings_page.rs
+++ b/devand-ui/src/app/components/settings_page.rs
@@ -163,21 +163,21 @@ impl SettingsPage {
                 <legend>{ "Profile" }</legend>
                 <div class="pure-control-group">
                     <label for="username">{ "Username:" }</label>
-                    <input type="text" name="username" id="username" value=&user.username readonly=true />
+                    <input type="text" name="username" id="username" class="pure-input-1" value=&user.username readonly=true />
                     <span class="pure-form-message-inline">{ "Username cannot be changed" }</span>
                 </div>
                 <div class="pure-control-group">
                     <label for="email">{ "Email:" }</label>
-                    <input type="text" name="email" id="email" value=&user.email oninput=self.link.callback(move |e: InputData| Msg::UpdateEmail(e.value)) />
+                    <input type="text" name="email" id="email" value=&user.email class="pure-input-1" oninput=self.link.callback(move |e: InputData| Msg::UpdateEmail(e.value)) />
                     { self.view_verify_email_button(user) }
                 </div>
                 <div class="pure-control-group">
                     <label for="visible_name">{ "Visible name:" }</label>
-                    <input type="text" name="visible_name" id="visible_name" value=&user.visible_name oninput=self.link.callback(move |e: InputData| Msg::UpdateVisibleName(e.value)) />
+                    <input type="text" name="visible_name" id="visible_name" class="pure-input-1" value=&user.visible_name oninput=self.link.callback(move |e: InputData| Msg::UpdateVisibleName(e.value)) />
                 </div>
                 <div class="pure-control-group">
                     <label for="bio">{ "Bio:" }</label>
-                    <textarea name="bio" class="pure-input-1-1" id="bio" value=&user.bio oninput=self.link.callback(move |e: InputData| Msg::UpdateBio(e.value)) />
+                    <textarea name="bio" class="pure-input-1" id="bio" value=&user.bio oninput=self.link.callback(move |e: InputData| Msg::UpdateBio(e.value)) />
                     <span class="pure-form-message-inline">{ "(max 160 characters)" }</span>
                 </div>
                 <div class="pure-control-group">

```

**Comment by alepez** [comment]
But now we have another problem, in the desktop version, inputs get huge

image

**Comment by alepez** [comment]
This patch on your branch should fix both desktop and mobile versions. I've added some "pure-u-*" to have responsive layout.

```diff
diff --git a/devand-ui/src/app/components/availability_table.rs b/devand-ui/src/app/components/availability_table.rs
index c897965..b3abf47 100644
--- a/devand-ui/src/app/components/availability_table.rs
+++ b/devand-ui/src/app/components/availability_table.rs
@@ -63,7 +63,7 @@ impl AvailabilityTable {
 
     fn view_week(&self, schedule: &WeekSchedule) -> Html {
         html! {
-            <fieldset>
+            <fieldset class="pure-u-1">
                 <legend>{ "Your current weekly schedule. Check your available hours. All hours are in UTC" }</legend>
                 { self.view_days(schedule) }
             </fieldset>
diff --git a/devand-ui/src/app/components/settings_page.rs b/devand-ui/src/app/components/settings_page.rs
index 0781d66..a8e727f 100644
--- a/devand-ui/src/app/components/settings_page.rs
+++ b/devand-ui/src/app/components/settings_page.rs
@@ -93,8 +93,8 @@ impl Component for SettingsPage {
 
     fn view(&self) -> Html {
         html! {
-            <div class="dashboard">
-                <h1>{ "Settings" }</h1>
+            <div class="dashboard pure-g">
+                <h1 class="pure-u-1">{ "Settings" }</h1>
                 {
                 if let Some(user) = &self.props.user {
                     self.view_settings_panel(user)
@@ -109,7 +109,7 @@ impl Component for SettingsPage {
 
 fn view_vacation_mode_panel() -> Html {
     html! {
-        <fieldset>
+        <fieldset class="pure-u-1">
             <legend>{ "You are currently in vacation mode" }</legend>
         </fieldset>
     }
@@ -159,25 +159,25 @@ impl SettingsPage {
 
     fn view_profile_panel(&self, user: &User) -> Html {
         html! {
-            <fieldset>
+            <fieldset class="pure-u-1 pure-u-md-1-4">
                 <legend>{ "Profile" }</legend>
                 <div class="pure-control-group">
                     <label for="username">{ "Username:" }</label>
-                    <input type="text" name="username" id="username" value=&user.username readonly=true />
+                    <input type="text" name="username" id="username" class="pure-input-1" value=&user.username readonly=true />
                     <span class="pure-form-message-inline">{ "Username cannot be changed" }</span>
                 </div>
                 <div class="pure-control-group">
                     <label for="email">{ "Email:" }</label>
-                    <input type="text" name="email" id="email" value=&user.email oninput=self.link.callback(move |e: InputData| Msg::UpdateEmail(e.value)) />
+                    <input type="text" name="email" id="email" value=&user.email class="pure-input-1" oninput=self.link.callback(move |e: InputData| Msg::UpdateEmail(e.value)) />
                     { self.view_verify_email_button(user) }
                 </div>
                 <div class="pure-control-group">
                     <label for="visible_name">{ "Visible name:" }</label>
-                    <input type="text" name="visible_name" id="visible_name" value=&user.visible_name oninput=self.link.callback(move |e: InputData| Msg::UpdateVisibleName(e.value)) />
+                    <input type="text" name="visible_name" id="visible_name" class="pure-input-1" value=&user.visible_name oninput=self.link.callback(move |e: InputData| Msg::UpdateVisibleName(e.value)) />
                 </div>
                 <div class="pure-control-group">
                     <label for="bio">{ "Bio:" }</label>
-                    <textarea name="bio" class="pure-input-1-1" id="bio" value=&user.bio oninput=self.link.callback(move |e: InputData| Msg::UpdateBio(e.value)) />
+                    <textarea name="bio" class="pure-input-1" id="bio" value=&user.bio oninput=self.link.callback(move |e: InputData| Msg::UpdateBio(e.value)) />
                     <span class="pure-form-message-inline">{ "(max 160 characters)" }</span>
                 </div>
                 <div class="pure-control-group">
@@ -195,7 +195,7 @@ impl SettingsPage {
         });
 
         html! {
-            <fieldset>
+            <fieldset class="pure-u-1">
                 <div class="pure-g">
                     <legend class="pure-u-1">{ "Languages" }</legend>
                     <div class="pure-u-1">
```

**Comment by alepez** [comment]
You should see something like this on desktop:

image

And this on phone:

image

**Comment by alepez** [comment]
Thankgs for your PR. I've merged and applied some minimal fixes.

**Comment by alepez** [comment]
And **welcome to the contributors**

**Pull request merged**
